package repo.services;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import repo.models.BlacklistLivres;
import repo.repositories.*;
import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@Service
public class BlacklistLivresService {
    private final BlacklistLivresRepository repo;

    @Autowired
    public BlacklistLivresService(BlacklistLivresRepository rep) {
        this.repo = rep;
    }

    public BlacklistLivres create(BlacklistLivres object) {
        return repo.save(object);
    }

    public List<BlacklistLivres> read() {
        return repo.findAll();
    }

    public Optional<BlacklistLivres> readById(int id) {
        return repo.findById(id);
    }

    public BlacklistLivres update(int id, BlacklistLivres object) {
        try {
            Optional<BlacklistLivres> optional = repo.findById(id);
            if (optional.isPresent()) {
                BlacklistLivres existing = optional.get();
                existing.setIdAdherant(object.getIdAdherant());
                existing.setIdLivre(object.getIdLivre());
                return repo.save(existing);
            }
            return null;
        } catch(Exception ex) {
            ex.printStackTrace();
            return null;
        }
    }

    public void delete(int id) {
        repo.deleteById(id);
    }
}