package repo.services;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import repo.models.HistoriquePret;
import repo.repositories.HistoriquePretRepository;
import java.util.List;
import java.util.Optional;

/*
   File generated By
   Christooj_Generation_Code
*/
@Service
public class HistoriquePretService {
    private final HistoriquePretRepository repo;

    @Autowired
    public HistoriquePretService(HistoriquePretRepository rep) {
        this.repo = rep;
    }

    public HistoriquePret create(HistoriquePret object) {
        return repo.save(object);
    }

    public List<HistoriquePret> read() {
        return repo.findAll();
    }

    public Optional<HistoriquePret> readById(int id) {
        return repo.findById(id);
    }

    public HistoriquePret update(int id, HistoriquePret object) {
        try {
            Optional<HistoriquePret> optional = repo.findById(id);
            if (optional.isPresent()) {
                HistoriquePret existing = optional.get();
                existing.setAdherant(object.getAdherant());
                existing.setExemplaire(object.getExemplaire());
                existing.setTypePret(object.getTypePret());
                existing.setDateDebut(object.getDateDebut());
                existing.setDateRetour(object.getDateRetour());
                return repo.save(existing);
            }
            return null;
        } catch(Exception ex) {
            ex.printStackTrace();
            return null;
        }
    }

    public void delete(int id) {
        repo.deleteById(id);
    }
}